[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "huggingface-hub>=0.33.2",
    "pandas>=2.3.1",
    "requests>=2.32.4",
    "streamlit>=1.46.1",
]
